import test from "node:test";
import assert from "node:assert/strict";
import { DEFAULT_VIEWS, topValues, bestLeadsPerCountry, scoreRow } from "./views.js";
import fs from "fs";
import path from "path";
import Papa from "papaparse";

// Reuse master.csv via relative path so the test reflects production data.
// Falls back to bundled sample.csv when master.csv isn't present (CI
// runs against a checkout where master.csv is gitignored — it lives in
// data/ locally but is generated by tools/verify_run.py). sample.csv is
// the canonical demo fixture tracked in the repo.
function loadRows() {
  const candidates = [
    "../data/master.csv",
    path.resolve("public/master.csv"),
    path.resolve("public/sample.csv"),
  ];
  for (const p of candidates) {
    try {
      const csv = fs.readFileSync(p, "utf8");
      return Papa.parse(csv, { header: true, skipEmptyLines: true }).data;
    } catch {
      /* try next */
    }
  }
  throw new Error(
    "views.test.js: no CSV fixture found (master.csv or sample.csv)",
  );
}

const rows = loadRows();

/**
 * Apply a view's filters to rows. __brand uses classifyBrand.
 */
import { classifyBrand } from "./brand.js";

function applyViewFilters(view, sourceRows) {
  const filters = view.filters || {};
  const brandFilter = filters.__brand;
  const bestCountry = filters.__bestInCountry;
  // __bestInCountry is a synthetic top-N selector — match by joining the
  // row's id against the ranked id set produced by bestLeadsPerCountry.
  let bestIdSet = null;
  if (bestCountry) {
    bestIdSet = new Set(
      bestLeadsPerCountry(sourceRows, bestCountry, 25).map((r) => r.id),
    );
  }
  return sourceRows.filter((row) => {
    if (brandFilter) {
      const b = classifyBrand(row);
      if (Array.isArray(brandFilter) ? !brandFilter.includes(b) : b !== brandFilter) {
        return false;
      }
    }
    if (bestCountry) {
      if (!row.id || !bestIdSet.has(row.id)) return false;
    }
    for (const [key, val] of Object.entries(filters)) {
      if (key === "__brand" || key === "__bestInCountry") continue;
      const cell = row[key];
      if (Array.isArray(val)) {
        if (!val.includes(cell)) return false;
      } else if (cell !== val) {
        return false;
      }
    }
    return true;
  });
}

test("default views: each one returns at least one row on master.csv", () => {
  for (const view of DEFAULT_VIEWS) {
    const matched = applyViewFilters(view, rows);
    assert.ok(
      matched.length > 0,
      `View "${view.name}" matched 0 rows — filter is broken: ${JSON.stringify(view.filters)}`
    );
  }
});

test("default views: PowerMatic view returns 50+ rows", () => {
  const v = DEFAULT_VIEWS.find((v) => v.id === "view-powermatic");
  const matched = applyViewFilters(v, rows);
  assert.ok(matched.length >= 50, `Got ${matched.length}`);
});

test("default views: Big players view returns some rows", () => {
  const v = DEFAULT_VIEWS.find((v) => v.id === "view-big-players");
  const matched = applyViewFilters(v, rows);
  assert.ok(matched.length > 0, `Got ${matched.length}`);
});

test("default views: Marketplace fishes view returns some rows", () => {
  const v = DEFAULT_VIEWS.find((v) => v.id === "view-marketplace");
  const matched = applyViewFilters(v, rows);
  assert.ok(matched.length > 0, `Got ${matched.length}`);
});

test("default views: per-country views (PL/CZ/SK) return rows", () => {
  for (const code of ["PL", "CZ", "SK"]) {
    const v = DEFAULT_VIEWS.find((v) => v.id === `view-${code.toLowerCase()}`);
    const matched = applyViewFilters(v, rows);
    assert.ok(matched.length > 0, `${code} view returned 0 rows`);
  }
});

test("topValues: returns sorted frequency list, skipping empty", () => {
  const data = [
    { tier: "hurtownik" },
    { tier: "hurtownik" },
    { tier: "marketplace" },
    { tier: "" },
    { tier: "brak" },
    { tier: "producent" },
  ];
  const result = topValues(data, "tier");
  assert.equal(result[0].value, "hurtownik");
  assert.equal(result[0].count, 2);
  // Should not include empty/brak
  assert.ok(!result.find((r) => r.value === "" || r.value === "brak"));
});

import { toggleFilterValue } from "./views.js";

test("toggleFilterValue: from undefined adds scalar", () => {
  assert.equal(toggleFilterValue(undefined, "PL"), "PL");
  assert.equal(toggleFilterValue(null, "PL"), "PL");
  assert.equal(toggleFilterValue("", "PL"), "PL");
});

test("toggleFilterValue: scalar same value returns undefined", () => {
  assert.equal(toggleFilterValue("PL", "PL"), undefined);
});

test("toggleFilterValue: scalar different value returns array of two", () => {
  assert.deepEqual(toggleFilterValue("PL", "CZ"), ["PL", "CZ"]);
});

test("toggleFilterValue: array add a value", () => {
  assert.deepEqual(toggleFilterValue(["PL"], "CZ"), ["PL", "CZ"]);
});

test("toggleFilterValue: array remove a value collapses to scalar", () => {
  assert.deepEqual(toggleFilterValue(["PL", "CZ"], "CZ"), "PL");
});

test("toggleFilterValue: array remove last value returns undefined", () => {
  assert.equal(toggleFilterValue(["PL"], "PL"), undefined);
});

test("best-per-country views exist for PL/CZ/SK and OTHER", () => {
  for (const id of ["view-best-pl", "view-best-cz", "view-best-sk", "view-best-other"]) {
    const v = DEFAULT_VIEWS.find((x) => x.id === id);
    assert.ok(v, `missing default view ${id}`);
    assert.ok(v.filters.__bestInCountry, `${id} should declare __bestInCountry`);
  }
});

test("best-per-country views: each returns rows when data exists for that country", () => {
  for (const code of ["PL", "CZ", "SK"]) {
    const v = DEFAULT_VIEWS.find((x) => x.id === `view-best-${code.toLowerCase()}`);
    const matched = applyViewFilters(v, rows);
    assert.ok(matched.length > 0, `Best ${code} returned 0 rows`);
    assert.ok(matched.length <= 25, `Best ${code} exceeded cap: ${matched.length}`);
    for (const r of matched) {
      assert.equal(r.kraj, code, `row ${r.id} has kraj=${r.kraj}, expected ${code}`);
      assert.ok(scoreRow(r) > 0, `row ${r.id} has non-positive score`);
    }
  }
});

test("bestLeadsPerCountry: excludes marketplace and detalista rows by score", () => {
  const data = [
    { id: "a", kraj: "PL", tier: "hurtownik", wolumen: "duży", cross_sell_potential: "High", confidence_wolumen: "🟢", powinowactwo_nabijarki: "wysoki" },
    { id: "b", kraj: "PL", tier: "marketplace", wolumen: "duży" },
    { id: "c", kraj: "PL", tier: "detalista" },
    { id: "d", kraj: "PL", tier: "producent", wolumen: "średni" },
  ];
  const best = bestLeadsPerCountry(data, "PL", 25);
  const ids = best.map((r) => r.id);
  assert.deepEqual(ids.sort(), ["a", "d"].sort());
});

test("bestLeadsPerCountry: OTHER bucket = non-PL/CZ/SK", () => {
  const data = [
    { id: "1", kraj: "PL", tier: "hurtownik", wolumen: "duży", cross_sell_potential: "High", confidence_wolumen: "🟢" },
    { id: "2", kraj: "DE", tier: "hurtownik", wolumen: "duży", cross_sell_potential: "High", confidence_wolumen: "🟢" },
    { id: "3", kraj: "UK", tier: "hurtownik", wolumen: "duży", cross_sell_potential: "High", confidence_wolumen: "🟢" },
    { id: "4", kraj: "CZ", tier: "hurtownik", wolumen: "duży", cross_sell_potential: "High", confidence_wolumen: "🟢" },
  ];
  const best = bestLeadsPerCountry(data, "OTHER", 25);
  const ids = best.map((r) => r.id).sort();
  assert.deepEqual(ids, ["2", "3"]);
});

test("bestLeadsPerCountry: respects limit", () => {
  const data = Array.from({ length: 10 }, (_, i) => ({
    id: `x${i}`,
    kraj: "PL",
    tier: "hurtownik",
    wolumen: "duży",
    cross_sell_potential: "High",
    confidence_wolumen: "🟢",
    powinowactwo_nabijarki: "wysoki",
  }));
  const best = bestLeadsPerCountry(data, "PL", 3);
  assert.equal(best.length, 3);
});

test("scoreRow: returns 0 for empty / unknown / marketplace-heavy row", () => {
  assert.equal(scoreRow({}), 0);
  assert.equal(scoreRow(null), 0);
  assert.equal(scoreRow({ kraj: "PL", tier: "marketplace", wolumen: "duży" }), 0);
});