#!/usr/bin/env python3
"""
BILLSzuka - Backup Cleanup Utility
Prunes bloated backup files in data/backups/:
  1. Deletes AppleDouble (._*) files generated by macOS.
  2. Deletes chained-timestamp files caused by recursive glob matching.
  3. Deduplicates identical backup files by content hash (MD5), keeping the newest copy per unique content.
"""

import re
import sys
import hashlib
from pathlib import Path
from collections import defaultdict

ROOT = Path(__file__).resolve().parent.parent
BACKUP_DIR = ROOT / "data" / "backups"

TIMESTAMP_RE = re.compile(r"_\d{8}_\d{6}")


def log(msg: str) -> None:
    print(f"[clean_backups] {msg}")


def clean_backups(dry_run: bool = False) -> dict[str, int]:
    if not BACKUP_DIR.exists():
        log(f"Backup directory {BACKUP_DIR} does not exist.")
        return {"total": 0, "apple_double": 0, "chained_ts": 0, "content_dups": 0, "kept": 0}

    all_files = list(BACKUP_DIR.glob("*"))
    log(f"Initial files in {BACKUP_DIR.name}/: {len(all_files)}")

    apple_double_files = []
    chained_ts_files = []
    single_ts_or_master_files = []

    for f in all_files:
        if f.name.startswith("._"):
            apple_double_files.append(f)
        else:
            ts_matches = TIMESTAMP_RE.findall(f.name)
            if len(ts_matches) > 1:
                chained_ts_files.append(f)
            else:
                single_ts_or_master_files.append(f)

    log(f"Found {len(apple_double_files)} AppleDouble (._*) files")
    log(f"Found {len(chained_ts_files)} chained-timestamp recursive backup files")
    log(f"Found {len(single_ts_or_master_files)} single-timestamp / master backup files")

    # Content deduplication among single-timestamp / master files
    by_hash = defaultdict(list)
    for f in single_ts_or_master_files:
        try:
            sz = f.stat().st_size
            h = hashlib.md5(f.read_bytes()).hexdigest()
            by_hash[(sz, h)].append(f)
        except OSError as e:
            log(f"Warning: could not read {f.name}: {e}")

    kept_files = []
    content_dup_files = []

    for (sz, h), file_group in by_hash.items():
        # Sort by mtime descending (newest first) or filename length ascending
        sorted_group = sorted(file_group, key=lambda x: (x.stat().st_mtime, -len(x.name)), reverse=True)
        kept_files.append(sorted_group[0])
        content_dup_files.extend(sorted_group[1:])

    to_delete = apple_double_files + chained_ts_files + content_dup_files
    log(f"Total files marked for deletion: {len(to_delete)}")
    log(f"Total unique backup files to KEEP: {len(kept_files)}")

    if dry_run:
        log("DRY RUN mode: no files were deleted.")
    else:
        deleted_count = 0
        for f in to_delete:
            try:
                f.unlink()
                deleted_count += 1
            except OSError as e:
                log(f"Error deleting {f.name}: {e}")
        log(f"Successfully deleted {deleted_count} redundant backup file(s).")

    return {
        "total_initial": len(all_files),
        "apple_double_deleted": len(apple_double_files),
        "chained_ts_deleted": len(chained_ts_files),
        "content_dups_deleted": len(content_dup_files),
        "kept": len(kept_files),
    }


if __name__ == "__main__":
    dry_run = "--dry-run" in sys.argv
    clean_backups(dry_run=dry_run)
